version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: irisimlsvr
    restart: always
    ports: 
      - 32782:1972
      - 32783:52773
      - 32784:53773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
  tf2jupyter:   # tensorflow with jupyter 
    build:
      context: ./tf2-jupyter-jdbc
    image: tf2-jupyter-jdbc:1.0.0-iml-template
    hostname: tf2jupyter
    restart: on-failure
    ports:
    - 8896:8888 # 8888 is the docker jupyter service port
    - 6026:6006 # 6006 is the tensorboard port
    volumes:
    - ./jupyter-samples:/tf   #shared volumes